package com.team3990.techscout.ui;

import androidx.lifecycle.LiveData;
import androidx.lifecycle.MutableLiveData;
import androidx.lifecycle.ViewModel;

import com.team3990.techscout.util.InsertDataSheetTask;
import com.team3990.techscout.database.dao.DataSheetDao;
import com.team3990.techscout.model.GameData;
import com.team3990.techscout.util.Event;

public final class GameDataEntryViewModel extends ViewModel implements InsertDataSheetTask.OnBackgroundComputationFinishesListener  {

    /** Properties */

    private final GameData mGameData;
    private final DataSheetDao mDataSheetDao;

    private final MutableLiveData<Event<String>> mDisplaySuccessSnackbar;

    /**
     * Constructor.
     *
     * Creates a Game Data Entry View Model instance
     * */
    public GameDataEntryViewModel(DataSheetDao dataSheetDao) {
        mGameData = new GameData();
        mDataSheetDao = dataSheetDao;
        mDisplaySuccessSnackbar = new MutableLiveData<>();
    }

    /** Getters */

    public GameData getMatchData() { return mGameData; }

    public LiveData<Event<String>> getDisplaySuccessSnackbar() { return mDisplaySuccessSnackbar; }

    public String getAutoGeneratedMatchDataSheetFileName() { return "Match " + mGameData.getMatchNumber() + " - " + mGameData.getTeamNumber() + " - " + mGameData.getRegionalName(); }

    /** Methods */

    public void saveAsDataSheet(String fileName) {
        mGameData.setFileName(fileName);

        // Save the match data instance onto the device's local SQL
        // database
        final InsertDataSheetTask insertionTask = new InsertDataSheetTask(this, mDataSheetDao);
        insertionTask.execute(mGameData);
    }

    @Override
    public void onInsertionCompleted(String s) {
        final Event displaySuccessSnackbarEvent = new Event<>(s);
        mDisplaySuccessSnackbar.setValue(displaySuccessSnackbarEvent);
    }

}
